import fs from 'fs';
import path from 'path';

// Per-airport SEO paragraphs generated by scripts/gen-content.mjs, stored as
// data/airport-content/<IATA>.json = { en: "...", ru: "...", ... }.
// Read via fs (not import) so the 6072 files never get bundled.
const DIR = path.join(process.cwd(), 'data/airport-content');

export function getAirportContent(iata: string, locale: string): string | null {
  try {
    const raw = fs.readFileSync(path.join(DIR, `${iata.toUpperCase()}.json`), 'utf8');
    const obj = JSON.parse(raw) as Record<string, string>;
    const text = obj[locale] || obj.en;
    return text && text.length > 20 ? text : null;
  } catch {
    return null;
  }
}
