import fs from 'fs';
import path from 'path';

// Per-airport SEO paragraphs generated by scripts/gen-content.mjs, stored as
// data/airport-content/<IATA>.json = { en: "...", ru: "...", ... }.
// Read via fs (not import) so the 6072 files never get bundled.
const DIR = path.join(process.cwd(), 'data/airport-content');

/**
 * 🔴 ГДЕ ЭТОТ ТЕКСТ ЕЩЁ ПОКАЗЫВАЕТСЯ — И ПОЧЕМУ ТОЛЬКО ТАМ (24.09.2026).
 *
 * Абзацы сгенерированы моделью (scripts/gen-content.mjs) на всех двенадцати языках, 6 073
 * файла. Это ровно то, что правило проекта запрещает: «писать нельзя, вычислять можно»;
 * AdSense отклонил сайт 03.08.2026 за «бесполезный контент», а Google держит 6 107 страниц в
 * «просканирована, не проиндексирована». Текст к тому же с ошибками, которые носитель видит
 * сразу: в немецком — несуществующее «Sitzfluggesellschaften», в русском — «актуальную
 * онлайн-табло», и с утверждениями без источника («compact single-terminal layout»).
 *
 * Снят он НЕ везде, и граница проведена по замеру, а не по вкусу:
 *
 *   · уникальности он страницам не добавляет. Замер на десяти английских аэропортах:
 *     сходство пар по пятисловным шинглам 0.198 с абзацем и 0.235 без него, максимум 0.289
 *     → 0.371. Дубли, за которые Google отверг пустые аэропорты в августе, начинались с
 *     0.975. Страницу держат данные — борт, рейсы, направления, вычисленный FAQ;
 *   · РУССКИЙ оставлен. Русские страницы — единственный канал, который приносит людей
 *     (98.3% визитов, Яндекс), и менять их текст без отдельного замера на этом канале значит
 *     рисковать единственным работающим ради гипотезы. В Google у них 106 показов за квартал,
 *     так что там терять нечего и в обратную сторону.
 *
 * Когда Google начнёт принимать страницы без абзаца, тот же шаг для русского — отдельное
 * решение с замером позиций в Вебмастере до и после. Сторожит границу
 * scripts/check-generated-prose.mjs.
 */
export const GENERATED_PROSE_LOCALES: ReadonlySet<string> = new Set(['ru']);

export function getAirportContent(iata: string, locale: string): string | null {
  // Никакого фолбэка на английский для снятых языков: прежний `obj[locale] || obj.en` отдал
  // бы английский сгенерированный текст на любой локали, где своего нет.
  if (!GENERATED_PROSE_LOCALES.has(locale)) return null;
  try {
    const raw = fs.readFileSync(path.join(DIR, `${iata.toUpperCase()}.json`), 'utf8');
    const obj = JSON.parse(raw) as Record<string, string>;
    const text = obj[locale] || obj.en;
    return text && text.length > 20 ? text : null;
  } catch {
    return null;
  }
}
