import fs from 'fs';
import path from 'path';

// Extended per-airport sections (transport / terminals / tips) generated by
// scripts/gen-content-extended.mjs, stored as
// data/airport-content-extended/<IATA>.json = { en: {transport,terminals,tips}, ru: {...}, ... }.
// Read via fs (not import) so the hub files never get bundled. Only ~top hubs have a file;
// everyone else returns null and the sections simply don't render.
const DIR = path.join(process.cwd(), 'data/airport-content-extended');

export type GuideTransfer = { dest: string; km: number; min: number };
export type GuideTransit = { line: string; op?: string | null; mode: string; dest: string; fare: string | null };
/** Verified reference tables — distances to nearby towns and the transport lines that
 *  actually leave the airport. Facts were harvested twice independently and only the
 *  agreeing rows were kept; a fare that the two passes did not agree on is null, and the
 *  row still renders (a line number and a direction are useful without a price). */
export type AirportGuide = { transfers: GuideTransfer[]; transit: GuideTransit[]; asOf: string };

export type AirportExtended = { transport: string; terminals: string; tips: string; guide: AirportGuide | null };

export function getAirportContentExtended(iata: string, locale: string): AirportExtended | null {
  try {
    const raw = fs.readFileSync(path.join(DIR, `${iata.toUpperCase()}.json`), 'utf8');
    const obj = JSON.parse(raw) as Record<string, Partial<AirportExtended>>;
    const s = obj[locale] || obj.en;
    if (!s) return null;
    const transport = (s.transport || '').trim();
    const terminals = (s.terminals || '').trim();
    const tips = (s.tips || '').trim();
    const g = (s as { guide?: AirportGuide }).guide ?? null;
    const guide = g && ((g.transfers?.length ?? 0) > 0 || (g.transit?.length ?? 0) > 0)
      ? { transfers: g.transfers ?? [], transit: g.transit ?? [], asOf: g.asOf ?? '' }
      : null;
    if (!transport && !terminals && !tips && !guide) return null;
    return { transport, terminals, tips, guide };
  } catch {
    return null;
  }
}
