import fs from 'fs';
import path from 'path';

// Extended per-airport sections (transport / terminals / tips) generated by
// scripts/gen-content-extended.mjs, stored as
// data/airport-content-extended/<IATA>.json = { en: {transport,terminals,tips}, ru: {...}, ... }.
// Read via fs (not import) so the hub files never get bundled. Only ~top hubs have a file;
// everyone else returns null and the sections simply don't render.
const DIR = path.join(process.cwd(), 'data/airport-content-extended');

export type AirportExtended = { transport: string; terminals: string; tips: string };

export function getAirportContentExtended(iata: string, locale: string): AirportExtended | null {
  try {
    const raw = fs.readFileSync(path.join(DIR, `${iata.toUpperCase()}.json`), 'utf8');
    const obj = JSON.parse(raw) as Record<string, Partial<AirportExtended>>;
    const s = obj[locale] || obj.en;
    if (!s) return null;
    const transport = (s.transport || '').trim();
    const terminals = (s.terminals || '').trim();
    const tips = (s.tips || '').trim();
    if (!transport && !terminals && !tips) return null;
    return { transport, terminals, tips };
  } catch {
    return null;
  }
}
