import fs from 'fs';
import path from 'path';

// Event pages (/event/[slug]) — data/events/<slug>.json, generated by
// scripts/gen-event-content.mjs. Tiny set, read once and cached; fs (not import)
// so content edits don't need a rebuild of the importing modules' chunks.
const DIR = path.join(process.cwd(), 'data/events');

export type EventAirport = { iata: string; km: number };
export type EventLocale = {
  title: string; description: string; h1: string; banner: string;
  intro: string; getting: string; leaving: string; tips: string;
};
export type EventData = {
  meta: {
    slug: string; name: string; startDate: string;
    venue: string; venueCity: string; airports: EventAirport[];
  };
  locales: Record<string, EventLocale>;
};

let cache: Map<string, EventData> | null = null;

function all(): Map<string, EventData> {
  if (!cache) {
    cache = new Map();
    try {
      for (const f of fs.readdirSync(DIR)) {
        if (!f.endsWith('.json')) continue;
        try {
          const d = JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')) as EventData;
          if (d?.meta?.slug) cache.set(d.meta.slug, d);
        } catch { /* skip broken file */ }
      }
    } catch { /* no events dir */ }
  }
  return cache;
}

export function getEvent(slug: string): EventData | null {
  return all().get(slug) ?? null;
}

export function getEventSlugs(): string[] {
  return [...all().keys()];
}

/** Events that involve this airport and haven't ended yet (shown as banners). */
export function getEventsForAirport(iata: string): EventData[] {
  const now = Date.now();
  const DAY = 86_400_000;
  return [...all().values()].filter(e =>
    e.meta.airports.some(a => a.iata === iata.toUpperCase())
    // keep the banner through the fly-home wave: event day + 3 days
    && now < Date.parse(e.meta.startDate) + 3 * DAY,
  );
}
