import fs from 'fs';
import path from 'path';

// Server-only readers for localized city & country names.
// Files generated by scripts/gen-places.mjs (keyed by the English value).
const CITY_FILE = path.join(process.cwd(), 'data/city-names.json');
const COUNTRY_FILE = path.join(process.cwd(), 'data/country-names.json');

let CITIES: Record<string, Record<string, string>> | null = null;
let COUNTRIES: Record<string, Record<string, string>> | null = null;

function ensure(): void {
  if (!CITIES) {
    try { CITIES = JSON.parse(fs.readFileSync(CITY_FILE, 'utf8')); } catch { CITIES = {}; }
  }
  if (!COUNTRIES) {
    try { COUNTRIES = JSON.parse(fs.readFileSync(COUNTRY_FILE, 'utf8')); } catch { COUNTRIES = {}; }
  }
}

export function getCityName(city: string, locale: string, fallback?: string): string {
  if (!city) return fallback ?? city;
  if (locale === 'en') return city;
  ensure();
  const n = CITIES![city]?.[locale];
  return n && n.length > 0 ? n : (fallback ?? city);
}

export function getCountryName(country: string, locale: string, fallback?: string): string {
  if (!country) return fallback ?? country;
  if (locale === 'en') return country;
  ensure();
  const n = COUNTRIES![country]?.[locale];
  return n && n.length > 0 ? n : (fallback ?? country);
}
