import fs from 'node:fs';
import path from 'node:path';

/**
 * Airline → destination facts for airports whose live board can never fill.
 *
 * 1,060 airports return no schedule from the flight provider under any code, so their boards
 * stay empty permanently and the page had nothing to show but "live board data is not available
 * right now". The question a traveller actually has about a small airport is not "what is on the
 * board this minute" — it is "who flies here, and where to". That is a fact, it is stable, and
 * Wikipedia keeps it current.
 *
 * Generated by scripts/gen-wiki-routes.mjs, which records the article title and the exact
 * revision each fact came from. Only facts are stored; no sentence is copied. Attribution is
 * rendered with the section — courtesy, and provenance an answer engine can follow.
 */
export type WikiAirline = { airline: string; destinations: string[] };
export type WikiRoutes = {
  airlines: WikiAirline[];
  /**
   * What the source says about scheduled service. `no_commercial_service` matters as much as
   * the routes: Adana Şakirpaşa lost all commercial flights in August 2024, so the provider's
   * empty answer is correct there and our own service data is simply stale. A page that can say
   * that is honest; one that promises a board is not.
   */
  status?: 'served' | 'no_commercial_service' | 'unclear';
  since?: string;
  source?: { title: string; revid: number; url: string } | null;
  via?: string;
};

let store: Record<string, WikiRoutes> | null = null;

function load(): Record<string, WikiRoutes> {
  if (store) return store;
  try {
    const p = path.join(process.cwd(), 'data', 'airport-wiki-routes.json');
    store = (JSON.parse(fs.readFileSync(p, 'utf8')) as { airports?: Record<string, WikiRoutes> }).airports ?? {};
  } catch { store = {}; }
  return store;
}

/** Facts for this airport, or null when we have none worth showing. */
export function getWikiRoutes(iata: string): WikiRoutes | null {
  const e = load()[iata.toUpperCase()];
  if (!e) return null;
  const hasAirlines = Array.isArray(e.airlines) && e.airlines.length > 0;
  const hasStatus = e.status === 'no_commercial_service';
  return hasAirlines || hasStatus ? e : null;
}

/** Does this airport have airline/destination facts to render? */
export function hasWikiAirlines(iata: string): boolean {
  const e = load()[iata.toUpperCase()];
  return !!e && Array.isArray(e.airlines) && e.airlines.length > 0;
}
